package main

import (
	"io"
	"net/http"
)

func handleLoginPage(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = io.WriteString(w, loginHTML)
}

func handleIndex(w http.ResponseWriter, req *http.Request) {
	if req.URL.Path != "/" {
		http.NotFound(w, req)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = io.WriteString(w, indexHTML)
}

const loginHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dual Protocol Script · 登录</title><style>
:root{color-scheme:dark;--bg:#07100f;--card:#101b19;--line:#243532;--text:#edf7f4;--muted:#8da49f;--green:#54e0a4;--red:#ff7b7b}
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;font:14px/1.5 Inter,system-ui,"Segoe UI",sans-serif;color:var(--text);background:radial-gradient(circle at 20% 10%,#173b32 0,transparent 34%),radial-gradient(circle at 90% 80%,#142c37 0,transparent 36%),var(--bg)}
.card{width:min(420px,calc(100vw - 32px));padding:34px;border:1px solid var(--line);border-radius:20px;background:#101b19ee;box-shadow:0 24px 80px #0008}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:14px;color:#052119;font-size:18px;font-weight:900;background:linear-gradient(135deg,var(--green),#b5ffd9)}
h1{font-size:25px;margin:20px 0 5px}.sub,.hint{color:var(--muted)}label{display:block;color:#b8c9c5;font-size:12px;font-weight:700;margin:24px 0 8px}input{width:100%;border:1px solid var(--line);border-radius:11px;padding:13px 14px;color:var(--text);background:#091310;outline:none}button{width:100%;margin-top:13px;padding:13px;border:0;border-radius:11px;background:var(--green);color:#062218;font-weight:800;cursor:pointer}button:disabled{opacity:.55}#err{min-height:22px;color:var(--red);font-size:12px;margin-top:10px}.hint{margin-top:18px;padding-top:16px;border-top:1px solid var(--line);font-size:11px}
</style></head><body><form class="card" id="login"><div class="mark">DP</div><h1>家宽出口控制面板</h1><p class="sub">Dual Protocol Script</p><label for="pw">访问密码</label><input id="pw" type="password" autocomplete="current-password" autofocus required><button id="submit">进入面板</button><div id="err"></div><div class="hint">面板由 TLS、随机路径和密码保护。REALITY 私钥绝不会发送到浏览器。</div></form>
<script>document.querySelector('#login').addEventListener('submit',async function(e){e.preventDefault();var b=document.querySelector('#submit'),x=document.querySelector('#err');b.disabled=true;x.textContent='';try{var r=await fetch('api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.querySelector('#pw').value})});var d=await r.json();if(!r.ok)throw new Error(d.error||'登录失败');location.reload()}catch(err){x.textContent=err.message}finally{b.disabled=false}});</script></body></html>`

const indexHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dual Protocol Script</title>
<style>
:root{color-scheme:dark;--bg:#08100f;--surface:#101a18;--surface2:#14211e;--line:#273734;--text:#edf7f4;--muted:#8da29e;--soft:#b9cbc6;--accent:#58e3a8;--amber:#f4c768;--red:#ff7777;--blue:#6cb9ff;--shadow:0 18px 55px #0006}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,system-ui,"Segoe UI",sans-serif}body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;background:radial-gradient(circle at 12% -5%,#173f35 0,transparent 27%),radial-gradient(circle at 100% 28%,#102a32 0,transparent 25%)}
button,select,input,textarea{font:inherit}.wrap{max-width:1240px;margin:auto;padding:30px 24px 56px}header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:28px}.brand{display:flex;gap:14px;align-items:center}.logo{width:46px;height:46px;display:grid;place-items:center;border-radius:13px;color:#06231a;font-weight:900;background:linear-gradient(135deg,var(--accent),#bdffdc)}.brand h1{font-size:20px;margin:0}.brand p{color:var(--muted);font-size:12px;margin:3px 0 0}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px}
.btn{cursor:pointer;border:1px solid var(--line);color:var(--soft);background:var(--surface);border-radius:10px;padding:9px 13px}.btn:hover{border-color:#48615b;color:var(--text)}.btn.primary{border-color:transparent;background:var(--accent);color:#06231a;font-weight:800}.btn.danger{color:#ffadad}.btn:disabled{opacity:.5;cursor:wait}.small{padding:6px 9px;font-size:11px}
.section-head{display:flex;justify-content:space-between;align-items:end;margin:26px 0 12px}.section-head h2{font-size:14px;margin:0}.section-head p{font-size:11px;color:var(--muted);margin:3px 0 0}.routing{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.route-card,.exit,.empty,.job{border:1px solid var(--line);background:linear-gradient(145deg,var(--surface2),var(--surface));border-radius:16px;box-shadow:0 8px 30px #0002}.route-card{padding:18px;border-left:3px solid var(--accent)}.route-top{display:flex;justify-content:space-between;align-items:center}.proto{display:flex;align-items:center;gap:11px}.proto-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:#20332f;color:var(--accent);font-weight:900}.proto h3{font-size:14px;margin:0}.proto p,.route-note{font-size:10px;color:var(--muted);margin:3px 0 0}.mode{font-size:10px;padding:4px 8px;border-radius:999px;color:var(--accent);background:#58e3a812;border:1px solid #58e3a82d}.route-controls{display:flex;gap:8px;margin-top:15px}.route-controls select{min-width:0;flex:1;color:var(--text);background:#0b1412;border:1px solid var(--line);border-radius:10px;padding:10px}.route-controls button{border:0;border-radius:10px;padding:0 16px;background:#263a35;color:var(--text);font-weight:700}.route-note{min-height:17px;margin-top:9px}.route-note.warn{color:var(--amber)}
.exits{display:grid;gap:10px}.exit{display:grid;grid-template-columns:34px minmax(150px,1.2fr) minmax(120px,.8fr) minmax(130px,.8fr) auto;align-items:center;gap:15px;padding:14px 16px}.dot{width:10px;height:10px;border-radius:50%;background:#53625f}.dot.up{background:var(--accent);box-shadow:0 0 0 5px #58e3a817}.dot.starting{background:var(--amber);animation:pulse 1s infinite}.dot.failed{background:var(--red)}@keyframes pulse{50%{opacity:.35}}.ip strong{display:block;font-size:15px}.ip span,.meta span{font-size:10px;color:var(--muted)}.country{font-weight:700}.chips{display:flex;flex-wrap:wrap;gap:5px}.chip{padding:3px 7px;border-radius:6px;font-size:9px;color:var(--blue);background:#6cb9ff12;border:1px solid #6cb9ff25}.exit-actions{display:flex;gap:7px}.exit-actions button{white-space:nowrap;border:1px solid var(--line);border-radius:8px;padding:7px 9px;background:#101a18;color:var(--soft)}.empty{padding:34px;text-align:center;color:var(--muted)}.empty b{display:block;color:var(--soft)}
.jobs{display:grid;gap:8px}.job{padding:13px 15px}.job-head{display:flex;justify-content:space-between}.steps{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.step{font-size:10px;padding:5px 8px;border:1px solid var(--line);border-radius:7px;color:var(--muted)}.step.ok{color:var(--accent)}.step.failed{color:var(--red)}.step.running{color:var(--amber)}.notice{display:none;margin:10px 0;padding:10px 13px;border:1px solid #ff777733;background:#ff77770d;border-radius:10px;color:#ffabab;font-size:11px}.notice.show{display:block}
.modal{position:fixed;inset:0;z-index:15;display:none;place-items:center;padding:20px;background:#020706c9;backdrop-filter:blur(7px)}.modal.open{display:grid}.dialog{width:min(540px,100%);max-height:calc(100vh - 40px);overflow:auto;border:1px solid var(--line);border-radius:18px;background:#101a18;box-shadow:var(--shadow);padding:21px}.dialog.wide{width:min(880px,100%)}.dialog-head{display:flex;justify-content:space-between;align-items:center}.dialog h3{margin:0;font-size:16px}.close{border:0;background:none;color:var(--muted);font-size:22px;cursor:pointer}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.full{grid-column:1/-1}.form-group{margin-top:18px;border-top:1px solid var(--line)}.form-group h4{margin:15px 0 0;font-size:12px;color:var(--accent)}.field{margin-top:14px}.field label{display:block;color:var(--muted);font-size:10px;font-weight:700;margin-bottom:7px}.field input,.field select,.field textarea{width:100%;padding:11px;color:var(--text);background:#091210;border:1px solid var(--line);border-radius:10px;outline:none}.field input:read-only{color:var(--muted)}.field textarea{min-height:92px;resize:vertical;word-break:break-all}.field-note{font-size:10px;color:var(--muted);margin-top:6px}.check{display:flex;align-items:center;gap:8px;margin-top:12px;color:var(--soft);font-size:11px}.check input{width:auto}.input-row{display:flex;gap:7px}.input-row input{flex:1}.config-warning{margin-top:16px;padding:10px 12px;border:1px solid #f4c76838;border-radius:10px;background:#f4c7680c;color:#f4d896;font-size:11px}.danger-warning{border-color:#ff777744;background:#ff77770c;color:#ffb5b5}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.hidden{display:none!important}.footer{margin-top:28px;padding-top:18px;border-top:1px solid var(--line);display:flex;justify-content:space-between;color:var(--muted);font-size:10px}.toast{position:fixed;right:22px;bottom:22px;z-index:30;max-width:min(430px,calc(100vw - 44px));padding:11px 14px;border-radius:10px;background:#20332e;border:1px solid #3f5d55;box-shadow:var(--shadow);transform:translateY(90px);opacity:0;transition:.2s}.toast.show{transform:none;opacity:1}.toast.bad{background:#341c1c;border-color:#633232}
@media(max-width:800px){.wrap{padding:18px 13px 42px}header{align-items:flex-start;flex-direction:column}.actions{justify-content:flex-start}.routing{grid-template-columns:1fr}.exit{grid-template-columns:24px 1fr auto;gap:9px}.exit .country,.exit .meta,.exit .chips{grid-column:2}.exit-actions{grid-column:3;grid-row:1/5;flex-direction:column}.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.footer{flex-direction:column;gap:5px}}
</style></head><body><div class="wrap">
<header><div class="brand"><div class="logo">DP</div><div><h1>Dual Protocol Script</h1><p id="stack">读取节点组合…</p></div></div><div class="actions"><button class="btn" id="share">分享链接</button><button class="btn" id="serviceControl">重启服务</button><button class="btn" id="panelSettings">面板设置</button><button class="btn" id="configure">节点配置</button><button class="btn danger" id="reinstall">重装组合</button><button class="btn" id="refresh">刷新节点池 ↻</button><button class="btn primary" id="add">＋ 新建出口</button></div></header>
<div class="notice" id="error"></div><div class="section-head"><div><h2>协议出口</h2><p>两个协议可分别选择 VPS 直连或指定的 VPN Gate 家宽出口</p></div></div><section class="routing" id="routing"></section>
<div class="section-head"><div><h2>VPN Gate 家宽出口</h2><p>切换节点时槽位与本地 SOCKS5 端口保持不变</p></div><span id="count"></span></div><section class="exits" id="exits"></section><section class="jobs" id="jobs"></section>
<div class="footer"><span>面板使用 HY2 域名 + TLS + 随机高位端口 + 随机路径 + 密码</span><span>SOCKS5 仅监听 127.0.0.1</span></div></div>

<div class="modal" id="exitModal"><div class="dialog"><div class="dialog-head"><h3>创建家宽出口</h3><button class="close" data-close="exitModal">×</button></div><div class="field"><label>地区</label><select id="region"></select><div class="field-note" id="regionInfo"></div></div><div class="field"><label>数量</label><input id="quantity" type="number" min="1" max="12" value="1"></div><div class="dialog-actions"><button class="btn" data-close="exitModal">取消</button><button class="btn primary" id="create">开始连接</button></div></div></div>

<div class="modal" id="configModal"><div class="dialog wide"><div class="dialog-head"><div><h3 id="configTitle">节点配置</h3><div class="field-note" id="configMode">读取当前组合…</div></div><button class="close" data-close="configModal">×</button></div>
<div class="field hidden" id="targetWrap"><label>要重装的协议组合</label><select id="cfgTarget"><option value="xhttp">VLESS XHTTP + Hysteria2</option><option value="reality">VLESS REALITY Vision + Hysteria2</option></select></div>
<div class="form-group"><h4>通用</h4><div class="form-grid"><div class="field"><label>节点名称 *</label><input id="cfgNodeName" maxlength="80"></div><div class="field"><label>客户端 uTLS 指纹 *</label><select id="cfgFP"><option value="chrome">chrome</option><option value="firefox">firefox</option></select></div></div></div>
<div class="form-group hidden" id="xhttpFields"><h4>VLESS XHTTP</h4><div class="form-grid"><div class="field"><label>XHTTP 域名 *</label><input id="cfgXHTTPDomain" autocomplete="off"></div><div class="field"><label>XHTTP 路径 *</label><div class="input-row"><input id="cfgXHTTPPath" autocomplete="off"><button class="btn small" type="button" data-generate="path">随机</button></div></div><div class="field"><label>XHTTP UUID *</label><div class="input-row"><input id="cfgXHTTPUUID" autocomplete="off"><button class="btn small" type="button" data-generate="xuuid">随机</button></div></div><div class="field"><label>本机后端端口 *</label><input id="cfgXHTTPBackendPort" type="number" min="1024" max="65535"></div></div><div class="config-warning">修改 XHTTP 域名前，请先确认新域名已正确解析到本 VPS，Cloudflare/CDN 代理已关闭，并放行 TCP 80/443。签发失败会自动恢复旧配置。</div></div>
<div class="form-group hidden" id="realityFields"><h4>VLESS REALITY Vision</h4><div class="form-grid"><div class="field"><label>客户端连接地址（VPS IP 或域名）*</label><input id="cfgRealityAddress"></div><div class="field"><label>目标 SNI *</label><input id="cfgRealitySNI"></div><div class="field"><label>REALITY UUID *</label><div class="input-row"><input id="cfgRealityUUID"><button class="btn small" type="button" data-generate="ruuid">随机</button></div></div><div class="field"><label>当前公钥（只读）</label><input id="cfgRealityPublicKey" readonly></div><div class="field"><label>当前 Short ID（只读）</label><input id="cfgRealityShortID" readonly></div><div class="field"><label>Hysteria2 ACME 邮箱 *</label><input id="cfgHY2ACMEEmail" type="email"></div><label class="check full"><input id="cfgRotateReality" type="checkbox">保存时生成并验证新 REALITY 密钥和 Short ID</label></div></div>
 <div class="form-group hidden" id="tcpBrutalFields"><h4>TCP Brutal 2.0（beta，仅 REALITY）</h4><label class="check"><input id="cfgTCPBrutalEnabled" type="checkbox">启用 TCP Brutal 2.0</label><div class="form-grid hidden" id="tcpBrutalBandwidthFields"><div class="field full"><label>每个公网 IP 下行总限速（Mbps）*</label><input id="cfgTCPBrutalDown" type="number" min="1" max="100000"><div class="field-note">默认 100 Mbps；每个公网 IP 独立计算，同一公网 IP 的多条 Reality TCP 连接共享该 IP 的总额度。上行不在本 beta 中限速。</div></div></div><div class="config-warning danger-warning">TCP Brutal 2.0 目前默认关闭。开启后很可能改变 TCP 行为特征，从而降低 REALITY 的伪装能力。这里配置的是服务端下行：按每个公网 IP 独立计算；启用前请确认你接受这一伪装性风险。</div></div>
<div class="form-group"><h4>Hysteria2</h4><div class="form-grid"><div class="field"><label>HY2 域名（也是面板 TLS 域名）*</label><input id="cfgHY2Domain"></div><div class="field"><label>HY2 密码 *</label><div class="input-row"><input id="cfgHY2Password" type="password"><button class="btn small" type="button" data-generate="hy2pass">随机</button></div></div><div class="field"><label>端口模式 *</label><select id="cfgHY2PortMode"><option value="hop">端口跳跃</option><option value="single">单端口</option></select></div><div class="field" id="singlePortField"><label>UDP 端口 *</label><input id="cfgHY2Port" type="number" min="1" max="65535"></div><div class="field" id="firstPortField"><label>跳跃起始/主端口 *</label><input id="cfgHY2FirstPort" type="number" min="1" max="65534"></div><div class="field" id="endPortField"><label>跳跃结束端口 *</label><input id="cfgHY2EndPort" type="number" min="2" max="65535"></div><div class="field" id="hopTypeField"><label>跳跃间隔模式 *</label><select id="cfgHopType"><option value="fixed">固定</option><option value="random">随机范围</option></select></div><div class="field" id="fixedHopField"><label>固定间隔（秒）*</label><input id="cfgHY2HopInterval" type="number" min="5" max="600"></div><div class="field" id="minHopField"><label>最小间隔（秒）*</label><input id="cfgHY2MinHopInterval" type="number" min="5" max="600"></div><div class="field" id="maxHopField"><label>最大间隔（秒）*</label><input id="cfgHY2MaxHopInterval" type="number" min="5" max="600"></div><div class="field"><label>混淆</label><select id="cfgHY2ObfsType"><option value="none">不启用（推荐）</option><option value="gecko">Gecko</option></select></div><div class="field hidden" id="obfsPasswordField"><label>Gecko 密码 *</label><div class="input-row"><input id="cfgHY2ObfsPassword" type="password"><button class="btn small" type="button" data-generate="geckopass">随机</button></div></div><div class="field hidden" id="geckoMinField"><label>Gecko 最小分片 *</label><input id="cfgGeckoMin" type="number" min="64" max="1500"></div><div class="field hidden" id="geckoMaxField"><label>Gecko 最大分片 *</label><input id="cfgGeckoMax" type="number" min="64" max="1500"></div></div><div class="config-warning">修改 HY2 域名会同时更换面板 TLS 域名。请先确认 DNS 直连本 VPS、CDN 代理关闭，并放行 ACME 所需端口；新证书验证成功后才会提交配置并清理旧域名证书。</div></div>
<div class="config-warning" id="configWarning">保存会先校验候选配置，再重启并检查代理；任何一步失败都会恢复旧配置。</div><div class="dialog-actions"><button class="btn" data-close="configModal">取消</button><button class="btn primary" id="saveConfig">保存并重启代理</button></div></div></div>

<div class="modal" id="shareModal"><div class="dialog wide"><div class="dialog-head"><h3>节点分享链接</h3><button class="close" data-close="shareModal">×</button></div><div class="field"><label>主节点</label><textarea id="mainURL" readonly></textarea><button class="btn small" data-copy="mainURL">复制主节点</button></div><div class="field"><label>Hysteria2</label><textarea id="hy2URL" readonly></textarea><button class="btn small" data-copy="hy2URL">复制 HY2</button></div><div class="field"><label>完整节点信息</label><textarea id="nodeInfo" readonly style="min-height:180px"></textarea></div><div class="dialog-actions"><button class="btn" data-close="shareModal">关闭</button><button class="btn primary" id="downloadLinks">下载 TXT</button></div></div></div>

<div class="modal" id="panelModal"><div class="dialog"><div class="dialog-head"><h3>面板设置</h3><button class="close" data-close="panelModal">×</button></div><div class="field"><label>TLS 域名（跟随 HY2，不在这里修改）</label><input id="panelDomain" readonly></div><div class="form-grid"><div class="field"><label>高位 TLS 端口</label><input id="panelPort" type="number" min="10240" max="65535"></div><div class="field"><label>最大家宽出口数</label><input id="panelMax" type="number" min="1" max="200"></div></div><div class="field"><label>随机访问路径（6-64 位，不含斜杠）</label><div class="input-row"><input id="panelPath"><button class="btn small" type="button" id="randomPanelPath">随机</button></div></div><div class="field"><label>新面板密码（留空表示不修改，至少 8 位）</label><div class="input-row"><input id="panelPassword" type="password" autocomplete="new-password"><button class="btn small" type="button" id="randomPanelPassword">随机</button></div></div><div class="config-warning">保存后面板服务会重启。请使用新端口、路径或密码重新登录；TLS 域名仍由节点的 HY2 域名决定。</div><div class="dialog-actions"><button class="btn" data-close="panelModal">取消</button><button class="btn primary" id="savePanel">保存并重启面板</button></div></div></div>
<div class="modal" id="serviceModal"><div class="dialog"><div class="dialog-head"><div><h3>一键重启代理服务</h3><div class="field-note" id="serviceStack">读取当前组合…</div></div><button class="close" data-close="serviceModal">×</button></div><div class="config-warning">重启会造成短暂断线。系统会在重启后检查服务是否处于 active 状态。</div><div class="form-grid"><button class="btn" style="margin-top:16px" data-restart-service="xray">重启 Xray</button><button class="btn" style="margin-top:16px" data-restart-service="hysteria2">重启 Hysteria2</button><button class="btn hidden" id="restartCaddy" style="margin-top:12px" data-restart-service="caddy">重启 Caddy</button><button class="btn primary" style="margin-top:12px" data-restart-service="all">重启当前组合全部服务</button></div><div class="dialog-actions"><button class="btn" data-close="serviceModal">关闭</button></div></div></div>
<div class="toast" id="toast"></div>

<script>
var $=function(s){return document.querySelector(s)};var state={router:{routes:[]},exits:[]},regions=[],nodeConfig=null,sourceNodeConfig=null,configAction='save',nodeLinks=null;
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
async function api(path,options){var res=await fetch(String(path).replace(/^\//,''),options||{}),data={};try{data=await res.json()}catch(_e){}if(res.status===401){location.reload();throw new Error('登录已失效')}if(!res.ok)throw new Error(data.error||('HTTP '+res.status));return data}
function toast(message,bad){var el=$('#toast');el.textContent=message;el.className='toast show'+(bad?' bad':'');clearTimeout(el.timer);el.timer=setTimeout(function(){el.className='toast'},4000)}
function setError(message){var el=$('#error');el.textContent=message||'';el.className='notice'+(message?' show':'')}
function randomToken(length){var chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789_-',bytes=new Uint8Array(length);crypto.getRandomValues(bytes);var out='';for(var i=0;i<length;i++)out+=chars[bytes[i]%chars.length];return out}
function routeOptions(selected){var html='<option value="0"'+(selected===0?' selected':'')+'>VPS 直连出口</option>';state.exits.forEach(function(exit){if(exit.status!=='up'&&exit.slot!==selected)return;var label='#'+exit.slot+' · '+(exit.node.country_code||'--')+' · '+(exit.exit_ip||exit.status);html+='<option value="'+exit.slot+'"'+(exit.slot===selected?' selected':'')+'>'+esc(label)+'</option>'});return html}
function renderRoutes(){var routes=state.router.routes||[];$('#routing').innerHTML=routes.map(function(route){var secondary=route.protocol==='hy2'?'UDP 入站 · TCP/UDP 目标':'Xray 主节点',icon=route.protocol==='hy2'?'H2':'VX',mode=route.mode==='direct'?'VPS 直连':('出口 #'+route.slot),note=route.note||(!route.ready?'出口暂不可用':'');return '<article class="route-card"><div class="route-top"><div class="proto"><div class="proto-icon">'+icon+'</div><div><h3>'+esc(route.label)+'</h3><p>'+secondary+'</p></div></div><span class="mode">'+esc(mode)+'</span></div><div class="route-controls"><select data-route="'+route.protocol+'">'+routeOptions(route.slot)+'</select><button data-save="'+route.protocol+'">应用</button></div><div class="route-note'+(note?' warn':'')+'">'+esc(note)+'</div></article>'}).join('')}
function routeChips(slot){return (state.router.routes||[]).filter(function(r){return r.slot===slot}).map(function(r){return '<span class="chip">'+esc(r.label)+'</span>'}).join('')}
function renderExits(){$('#count').textContent=state.exits.length?state.exits.length+' 条':'';if(!state.exits.length){$('#exits').innerHTML='<div class="empty"><b>还没有家宽出口</b>点击“新建出口”，按地区连接 VPN Gate 志愿节点。</div>';return}$('#exits').innerHTML=state.exits.map(function(exit){var node=exit.node||{},status=exit.status||'failed',statusText={up:'已连通',starting:'连接中',failed:'失败',stopped:'已停止'}[status]||status;return '<article class="exit"><div class="dot '+esc(status)+'" title="'+esc(statusText)+'"></div><div class="ip"><strong>'+esc(exit.exit_ip||statusText)+'</strong><span>#'+exit.slot+' · '+esc(node.hostname||'')+'</span></div><div class="country">'+esc(node.country_code||'--')+' <span style="color:var(--muted);font-size:10px">'+esc(node.country||'')+'</span></div><div class="meta"><b>127.0.0.1:'+exit.port+'</b><br><span>'+esc(exit.error||statusText)+'</span></div><div class="chips">'+routeChips(exit.slot)+'</div><div class="exit-actions"><button data-swap="'+exit.slot+'" '+(status==='starting'?'disabled':'')+'>换 IP</button><button data-stop="'+exit.slot+'">停止</button></div></article>'}).join('')}
function renderJobs(jobs){if(!jobs||!jobs.length){$('#jobs').innerHTML='';return}$('#jobs').innerHTML='<div class="section-head"><div><h2>后台任务</h2><p>失效节点会自动尝试同地区候选</p></div></div>'+jobs.map(function(job){return '<article class="job"><div class="job-head"><strong>'+esc(job.summary)+'</strong>'+(job.done?'<button class="btn small" data-dismiss="'+job.id+'">关闭</button>':'<span style="color:var(--amber)">进行中</span>')+'</div><div class="steps">'+job.steps.map(function(step){return '<span class="step '+esc(step.status)+'" title="'+esc(step.detail||'')+'">'+esc(step.label)+' · '+esc(step.status)+'</span>'}).join('')+'</div></article>'}).join('')}
async function load(){try{state=await api('api/status');setError('');var stack=state.router.stack==='xhttp_hy2'?'VLESS XHTTP + Hysteria2':state.router.stack==='reality_hy2'?'VLESS REALITY Vision + Hysteria2':'节点配置未识别';$('#stack').textContent=stack+' · 网页面板管理节点、出口与重装';if(state.router.last_error)setError(state.router.last_error);renderRoutes();renderExits();renderJobs(await api('api/jobs'))}catch(err){setError(err.message)}}
async function loadRegions(){regions=await api('api/regions');$('#region').innerHTML='<option value="">任意地区（速度优先）</option>'+regions.map(function(r){return '<option value="'+esc(r.code)+'">'+esc(r.code+' · '+r.name+' · '+r.available+' 个')+'</option>'}).join('');updateRegionInfo()}
function updateRegionInfo(){var code=$('#region').value,region=regions.find(function(r){return r.code===code});$('#regionInfo').textContent=region?('可用 '+region.available+' · 最低延迟 '+region.best_ping+' ms · 标称 '+region.best_speed_mbps.toFixed(0)+' Mbps'):'从全部地区按标称速度选择'}
function setValue(id,value){var el=$(id);if(el)el.value=value==null?'':value}function numberValue(id){return Number($(id).value)||0}
function updateConfigFields(){var xhttp=nodeConfig&&nodeConfig.main_mode==='xhttp',reality=nodeConfig&&nodeConfig.main_mode==='reality';$('#xhttpFields').classList.toggle('hidden',!xhttp);$('#realityFields').classList.toggle('hidden',!reality);$('#tcpBrutalFields').classList.toggle('hidden',!reality);$('#tcpBrutalBandwidthFields').classList.toggle('hidden',!reality||!$('#cfgTCPBrutalEnabled').checked);var hopping=$('#cfgHY2PortMode').value==='hop';$('#singlePortField').classList.toggle('hidden',hopping);['#firstPortField','#endPortField','#hopTypeField'].forEach(function(id){$(id).classList.toggle('hidden',!hopping)});var random=hopping&&$('#cfgHopType').value==='random';$('#fixedHopField').classList.toggle('hidden',!hopping||random);$('#minHopField').classList.toggle('hidden',!random);$('#maxHopField').classList.toggle('hidden',!random);var gecko=$('#cfgHY2ObfsType').value==='gecko';['#obfsPasswordField','#geckoMinField','#geckoMaxField'].forEach(function(id){$(id).classList.toggle('hidden',!gecko)})}
function populateNodeConfig(config){nodeConfig=config;$('#configMode').textContent=(config.main_mode==='xhttp'?'VLESS XHTTP + Hysteria2':'VLESS REALITY Vision + Hysteria2')+(configAction==='reinstall'?' · 完整重装':' · 修改现有配置');setValue('#cfgNodeName',config.node_name);setValue('#cfgFP',config.fp);setValue('#cfgXHTTPDomain',config.xhttp_domain);setValue('#cfgXHTTPPath',config.xhttp_path);setValue('#cfgXHTTPUUID',config.xhttp_uuid);setValue('#cfgXHTTPBackendPort',config.xhttp_backend_port||10080);setValue('#cfgRealityAddress',config.reality_address);setValue('#cfgRealitySNI',config.reality_sni);setValue('#cfgRealityUUID',config.reality_uuid);setValue('#cfgRealityPublicKey',config.reality_public_key);setValue('#cfgRealityShortID',config.reality_short_id);setValue('#cfgHY2ACMEEmail',config.hy2_acme_email);$('#cfgRotateReality').checked=!!config.rotate_reality_keys;$('#cfgTCPBrutalEnabled').checked=!!config.tcp_brutal_enabled;setValue('#cfgTCPBrutalDown',config.tcp_brutal_down_mbps||100);setValue('#cfgHY2Domain',config.hy2_domain);setValue('#cfgHY2Password',config.hy2_password);setValue('#cfgHY2PortMode',config.hy2_port_mode);setValue('#cfgHY2Port',config.hy2_port);setValue('#cfgHY2FirstPort',config.hy2_first_port);setValue('#cfgHY2EndPort',config.hy2_end_port);setValue('#cfgHY2HopInterval',config.hy2_hop_interval||25);setValue('#cfgHY2MinHopInterval',config.hy2_min_hop_interval||15);setValue('#cfgHY2MaxHopInterval',config.hy2_max_hop_interval||25);setValue('#cfgHopType',(config.hy2_min_hop_interval||config.hy2_max_hop_interval)?'random':'fixed');setValue('#cfgHY2ObfsType',config.hy2_obfs_type||'none');setValue('#cfgHY2ObfsPassword',config.hy2_obfs_password);setValue('#cfgGeckoMin',config.hy2_gecko_min_packet_size||512);setValue('#cfgGeckoMax',config.hy2_gecko_max_packet_size||1200);updateConfigFields()}
function targetConfig(source,target){var c=JSON.parse(JSON.stringify(source));c.main_mode=target;c.stack_mode=target==='xhttp'?'xhttp_hy2':'reality_hy2';c.hy2_cert_source=target==='xhttp'?'caddy':'acme';c.tcp_brutal_down_mbps=c.tcp_brutal_down_mbps||100;if(target==='xhttp'){if(source.main_mode!=='xhttp'){c.xhttp_domain='';c.xhttp_path='/'+randomToken(14);c.xhttp_uuid=crypto.randomUUID();c.xhttp_backend_port=10080}c.rotate_reality_keys=false;c.tcp_brutal_enabled=false}else{if(source.main_mode!=='reality'){c.reality_address=c.hy2_domain;c.reality_sni='www.microsoft.com';c.reality_uuid=crypto.randomUUID();c.reality_public_key='';c.reality_short_id='';c.tcp_brutal_enabled=false}c.rotate_reality_keys=true}return c}
function collectNodeConfig(){var c=Object.assign({},nodeConfig);c.node_name=$('#cfgNodeName').value.trim();c.fp=$('#cfgFP').value;c.xhttp_domain=$('#cfgXHTTPDomain').value.trim();c.xhttp_path=$('#cfgXHTTPPath').value.trim();c.xhttp_uuid=$('#cfgXHTTPUUID').value.trim();c.xhttp_backend_port=numberValue('#cfgXHTTPBackendPort');c.reality_address=$('#cfgRealityAddress').value.trim();c.reality_sni=$('#cfgRealitySNI').value.trim();c.reality_uuid=$('#cfgRealityUUID').value.trim();c.rotate_reality_keys=$('#cfgRotateReality').checked;c.tcp_brutal_enabled=$('#cfgTCPBrutalEnabled').checked;c.tcp_brutal_down_mbps=numberValue('#cfgTCPBrutalDown');c.hy2_domain=$('#cfgHY2Domain').value.trim();c.hy2_password=$('#cfgHY2Password').value;c.hy2_port_mode=$('#cfgHY2PortMode').value;c.hy2_port=numberValue('#cfgHY2Port');c.hy2_first_port=numberValue('#cfgHY2FirstPort');c.hy2_end_port=numberValue('#cfgHY2EndPort');if(c.hy2_port_mode==='hop'&&$('#cfgHopType').value==='random'){c.hy2_hop_interval=0;c.hy2_min_hop_interval=numberValue('#cfgHY2MinHopInterval');c.hy2_max_hop_interval=numberValue('#cfgHY2MaxHopInterval')}else{c.hy2_hop_interval=numberValue('#cfgHY2HopInterval');c.hy2_min_hop_interval=0;c.hy2_max_hop_interval=0}c.hy2_acme_email=$('#cfgHY2ACMEEmail').value.trim();c.hy2_obfs_type=$('#cfgHY2ObfsType').value;c.hy2_obfs_password=$('#cfgHY2ObfsPassword').value;c.hy2_gecko_min_packet_size=numberValue('#cfgGeckoMin');c.hy2_gecko_max_packet_size=numberValue('#cfgGeckoMax');return c}
function invalidField(id,message){toast(message,true);var el=$(id);if(el){el.focus();el.scrollIntoView({behavior:'smooth',block:'center'})}return false}
function validUUID(value){return /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(value)}
function plausibleDomain(value){return value.length<=253&&value.indexOf('.')>0&&!/[\s/:]/.test(value)}
function validateNodeConfigForm(c){if(!c.node_name||c.node_name.length>80)return invalidField('#cfgNodeName','请填写 1-80 个字符的节点名称');if(!plausibleDomain(c.hy2_domain))return invalidField('#cfgHY2Domain','请填写有效的 HY2 域名');if(!c.hy2_password||c.hy2_password.length>256)return invalidField('#cfgHY2Password','请填写 HY2 密码（1-256 个字符）');if(c.tcp_brutal_down_mbps<1||c.tcp_brutal_down_mbps>100000)return invalidField('#cfgTCPBrutalDown','TCP Brutal 每个公网 IP 下行限速必须在 1-100000 Mbps');if(c.main_mode==='xhttp'&&c.tcp_brutal_enabled)return invalidField('#cfgTCPBrutalEnabled','TCP Brutal 2.0 只允许用于 REALITY 节点');var reserved=[80,443,2053,8443];if(c.hy2_port_mode==='single'){if(c.hy2_port<1||c.hy2_port>65535||reserved.includes(c.hy2_port))return invalidField('#cfgHY2Port','HY2 单端口必须在 1-65535，且不能使用 80/443/2053/8443')}else{if(c.hy2_first_port<1||c.hy2_end_port>65535||c.hy2_end_port<=c.hy2_first_port)return invalidField('#cfgHY2FirstPort','请填写有效的 HY2 跳跃端口范围');if(reserved.some(function(p){return p>=c.hy2_first_port&&p<=c.hy2_end_port}))return invalidField('#cfgHY2FirstPort','HY2 跳跃范围不能包含 80/443/2053/8443');if($('#cfgHopType').value==='random'){if(c.hy2_min_hop_interval<5||c.hy2_max_hop_interval<c.hy2_min_hop_interval||c.hy2_max_hop_interval>600)return invalidField('#cfgHY2MinHopInterval','随机跳跃最小/最大间隔必须完整填写，范围为 5-600 秒')}else if(c.hy2_hop_interval<5||c.hy2_hop_interval>600)return invalidField('#cfgHY2HopInterval','固定跳跃间隔必须在 5-600 秒')}if(c.hy2_obfs_type==='gecko'){if(!c.hy2_obfs_password)return invalidField('#cfgHY2ObfsPassword','启用 Gecko 时必须填写混淆密码');if(c.hy2_gecko_min_packet_size<64||c.hy2_gecko_max_packet_size<c.hy2_gecko_min_packet_size||c.hy2_gecko_max_packet_size>1500)return invalidField('#cfgGeckoMin','Gecko 分片必须在 64-1500，且最大值不能小于最小值')}if(c.main_mode==='xhttp'){if(!plausibleDomain(c.xhttp_domain))return invalidField('#cfgXHTTPDomain','请填写有效的 XHTTP 域名');if(c.xhttp_domain.toLowerCase()===c.hy2_domain.toLowerCase())return invalidField('#cfgXHTTPDomain','XHTTP 与 HY2 必须使用两个不同域名');if(!c.xhttp_path||c.xhttp_path==='/'||c.xhttp_path.charAt(0)!=='/')return invalidField('#cfgXHTTPPath','请填写以 / 开头的非根 XHTTP 路径');if(!validUUID(c.xhttp_uuid))return invalidField('#cfgXHTTPUUID','XHTTP UUID 格式无效');if(c.xhttp_backend_port<1024||c.xhttp_backend_port>65535)return invalidField('#cfgXHTTPBackendPort','XHTTP 后端端口必须在 1024-65535')}else{if(!c.reality_address)return invalidField('#cfgRealityAddress','请填写 REALITY 客户端连接地址');if(!plausibleDomain(c.reality_sni))return invalidField('#cfgRealitySNI','请填写有效的 REALITY 目标 SNI');if(!validUUID(c.reality_uuid))return invalidField('#cfgRealityUUID','REALITY UUID 格式无效');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.hy2_acme_email))return invalidField('#cfgHY2ACMEEmail','请填写有效的 Hysteria2 ACME 邮箱')}return true}
function changedNodeDomains(c){var changes=[];if(!sourceNodeConfig)return changes;var oldHY2=String(sourceNodeConfig.hy2_domain||'').toLowerCase(),newHY2=String(c.hy2_domain||'').toLowerCase();if(oldHY2!==newHY2)changes.push('HY2：'+(oldHY2||'未设置')+' → '+newHY2);if(c.main_mode==='xhttp'){var oldX=String(sourceNodeConfig.xhttp_domain||'').toLowerCase(),newX=String(c.xhttp_domain||'').toLowerCase();if(oldX!==newX)changes.push('XHTTP：'+(oldX||'未设置')+' → '+newX)}return changes}
async function openNodeConfig(action){configAction=action;sourceNodeConfig=await api('api/node-config');$('#targetWrap').classList.toggle('hidden',action!=='reinstall');$('#configTitle').textContent=action==='reinstall'?'一键重装协议组合':'节点配置';$('#saveConfig').textContent=action==='reinstall'?'确认重装组合':'保存并重启代理';$('#configWarning').className='config-warning'+(action==='reinstall'?' danger-warning':'');$('#configWarning').textContent=action==='reinstall'?'请完整填写所有带 * 的必填项后再开始。重装会短暂中断连接，并可能安装或移除 Caddy；域名必须正确解析到本 VPS、关闭 CDN 代理并放行 80/443。失败会恢复原配置。':'保存会先校验全部必填项和候选配置，再重启并检查代理。若更改域名，会先取得并验证新证书，成功后才清理旧证书；失败会恢复旧配置。';if(action==='reinstall'){var target=sourceNodeConfig.main_mode==='xhttp'?'reality':'xhttp';setValue('#cfgTarget',target);populateNodeConfig(targetConfig(sourceNodeConfig,target))}else populateNodeConfig(sourceNodeConfig);$('#configModal').classList.add('open')}
async function copyText(id){var text=$('#'+id).value;try{await navigator.clipboard.writeText(text)}catch(_e){var el=$('#'+id);el.select();document.execCommand('copy')}toast('已复制')}

document.addEventListener('click',async function(event){var close=event.target.closest('[data-close]');if(close){$('#'+close.dataset.close).classList.remove('open');return}var save=event.target.closest('[data-save]');if(save){var protocol=save.dataset.save,select=document.querySelector('[data-route="'+protocol+'"]');save.disabled=true;try{await api('api/bind?protocol='+encodeURIComponent(protocol)+'&slot='+select.value,{method:'POST'});toast('协议出口已更新');await load()}catch(err){toast(err.message,true)}finally{save.disabled=false}return}var swap=event.target.closest('[data-swap]');if(swap){swap.disabled=true;try{await api('api/swap?slot='+swap.dataset.swap,{method:'POST'});toast('正在切换家宽 IP');await load()}catch(err){toast(err.message,true)}finally{swap.disabled=false}return}var stop=event.target.closest('[data-stop]');if(stop){if(!confirm('停止出口 #'+stop.dataset.stop+'？绑定协议会切回 VPS 直连。'))return;try{await api('api/stop?slot='+stop.dataset.stop,{method:'POST'});await load()}catch(err){toast(err.message,true)}return}var dismiss=event.target.closest('[data-dismiss]');if(dismiss){await api('api/jobs/dismiss?id='+dismiss.dataset.dismiss,{method:'POST'});await load();return}var generate=event.target.closest('[data-generate]');if(generate){if(generate.dataset.generate==='path')setValue('#cfgXHTTPPath','/'+randomToken(14));else if(generate.dataset.generate==='xuuid')setValue('#cfgXHTTPUUID',crypto.randomUUID());else if(generate.dataset.generate==='ruuid')setValue('#cfgRealityUUID',crypto.randomUUID());else if(generate.dataset.generate==='hy2pass')setValue('#cfgHY2Password',randomToken(32));else if(generate.dataset.generate==='geckopass')setValue('#cfgHY2ObfsPassword',randomToken(32));return}var copy=event.target.closest('[data-copy]');if(copy){await copyText(copy.dataset.copy)}});
document.addEventListener('click',async function(event){var b=event.target.closest('[data-restart-service]');if(!b)return;var service=b.dataset.restartService,label=service==='all'?'当前组合全部服务':service;if(!confirm('确认重启 '+label+'？当前连接会短暂中断。'))return;b.disabled=true;var old=b.textContent;b.textContent='重启并检查中…';try{var result=await api('api/services/restart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:service})});toast('重启成功：'+Object.keys(result.results).join('、'))}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent=old}});
$('#add').onclick=async function(){try{await loadRegions();$('#exitModal').classList.add('open')}catch(err){toast(err.message,true)}};$('#region').onchange=updateRegionInfo;$('#create').onclick=async function(){var b=this,count=Math.max(1,Math.min(12,Number($('#quantity').value)||1));b.disabled=true;try{await api('api/provision?region='+encodeURIComponent($('#region').value)+'&count='+count,{method:'POST'});$('#exitModal').classList.remove('open');toast('创建任务已提交');await load()}catch(err){toast(err.message,true)}finally{b.disabled=false}};
$('#refresh').onclick=async function(){var b=this;b.disabled=true;try{var result=await api('api/refresh',{method:'POST'});toast('已刷新 '+result.count+' 个节点');await load()}catch(err){toast(err.message,true)}finally{b.disabled=false}};
$('#serviceControl').onclick=function(){var stack=state.router.stack;if(stack!=='xhttp_hy2'&&stack!=='reality_hy2'){toast('当前节点配置未识别，不能安全重启组合服务',true);return}var xhttp=stack==='xhttp_hy2';$('#serviceStack').textContent=xhttp?'当前组合：VLESS XHTTP + Hysteria2（含 Caddy）':'当前组合：VLESS REALITY Vision + Hysteria2（不安装 Caddy）';$('#restartCaddy').classList.toggle('hidden',!xhttp);$('#serviceModal').classList.add('open')};
$('#configure').onclick=async function(){var b=this;b.disabled=true;try{await openNodeConfig('save')}catch(err){toast(err.message,true)}finally{b.disabled=false}};$('#reinstall').onclick=async function(){var b=this;b.disabled=true;try{await openNodeConfig('reinstall')}catch(err){toast(err.message,true)}finally{b.disabled=false}};
$('#cfgTarget').onchange=function(){populateNodeConfig(targetConfig(sourceNodeConfig,this.value))};$('#cfgHY2PortMode').onchange=updateConfigFields;$('#cfgHopType').onchange=updateConfigFields;$('#cfgHY2ObfsType').onchange=updateConfigFields;$('#cfgTCPBrutalEnabled').onchange=updateConfigFields;
$('#saveConfig').onclick=async function(){if(!nodeConfig)return;var reinstall=configAction==='reinstall',payload=collectNodeConfig();if(!validateNodeConfigForm(payload))return;var changes=changedNodeDomains(payload),question=reinstall?'确认完整重装所选协议组合？节点会暂时断开，成功后面板也会重启。':'保存后将立即重启代理服务；若健康检查失败会自动回滚。继续吗？';if(changes.length)question='检测到域名变更：\n'+changes.join('\n')+'\n\n请再次确认：新域名已正确解析到本 VPS，Cloudflare/CDN 代理已关闭，TCP 80/443 与 HY2 UDP 端口已放行。系统会先签发并验证新证书，成功后再清理旧证书；失败则自动恢复。\n\n继续吗？';if(payload.tcp_brutal_enabled)question='警告：TCP Brutal 2.0 很可能改变 TCP 行为特征，从而降低 REALITY 的伪装能力；下行限速按每个公网 IP 独立计算，同一公网 IP 的多条 Reality TCP 连接共享该 IP 的总额度；上行不做限速。\n\n'+question;if(!confirm(question))return;var b=this;b.disabled=true;b.textContent=reinstall?'重装中，请勿关闭…':'校验、换证并重启中…';try{var result=await api(reinstall?'api/node-reinstall':'api/node-config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#configModal').classList.remove('open');if(result.warning)toast(result.warning,true);else toast(reinstall?'协议组合重装完成':'节点配置已保存');if(result.panel_restart)alert('HY2 域名和面板证书已更新，面板将重启。请稍后使用域名 '+result.panel_domain+'、原面板端口和路径重新打开。');else await load()}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent=reinstall?'确认重装组合':'保存并重启代理'}};
$('#share').onclick=async function(){var b=this;b.disabled=true;try{nodeLinks=await api('api/node-links');setValue('#mainURL',nodeLinks.main_url);setValue('#hy2URL',nodeLinks.hy2_url);setValue('#nodeInfo',nodeLinks.info);$('#shareModal').classList.add('open')}catch(err){toast(err.message,true)}finally{b.disabled=false}};$('#downloadLinks').onclick=function(){if(!nodeLinks)return;var blob=new Blob([nodeLinks.info+'\n\n主节点：\n'+nodeLinks.main_url+'\n\nHysteria2：\n'+nodeLinks.hy2_url+'\n'],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dual-protocol-nodes.txt';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)};
$('#panelSettings').onclick=async function(){var b=this;b.disabled=true;try{var c=await api('api/panel-config');setValue('#panelDomain',c.domain);setValue('#panelPort',c.port);setValue('#panelPath',c.path);setValue('#panelMax',c.max_exits);setValue('#panelPassword','');$('#panelModal').classList.add('open')}catch(err){toast(err.message,true)}finally{b.disabled=false}};$('#randomPanelPath').onclick=function(){setValue('#panelPath',randomToken(24))};$('#randomPanelPassword').onclick=function(){setValue('#panelPassword',randomToken(28))};$('#savePanel').onclick=async function(){if(!confirm('保存后面板将重启，当前页面会断开。继续吗？'))return;var b=this,payload={domain:$('#panelDomain').value,port:numberValue('#panelPort'),path:$('#panelPath').value.trim(),max_exits:numberValue('#panelMax'),new_password:$('#panelPassword').value,password_configured:true};b.disabled=true;b.textContent='保存中…';try{var r=await api('api/panel-config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#panelModal').classList.remove('open');alert('面板设置已保存并将重启。新地址：\nhttps://'+r.domain+':'+r.port+'/'+r.path+'/\n\n若修改了密码，请使用新密码登录。')}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent='保存并重启面板'}};
load();setInterval(load,4000);
</script></body></html>`
